apiVersion: v1
kind: Service
metadata:
  name: playlist-api-service
  namespace: camilosm
spec:
  type: NodePort
  selector:
    app: playlist-recommender-api
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 50035
    protocol: TCP
    name: http
